### ISSUE TITLE
Webservices.c variáveis não iniciadas

### ISSUE THREAD

**Issue by jhonatafernandes** [joaovitor7/tmc#1]
Dentro do webservice gerado, as variáveis retiradas do EPT não estão sendo iniciadas. Com isso, ao enviar um GET, o cliente é obrigado a determinar o valor de todas as variáveis.
Se as variáveis forem iniciadas com o valor 0, esse problema acaba.

**Comment by joaovitor7** [comment]
Adicionei suas modificação Jhonata. Obrigado pela contribuição!
